Repository 4n4nd/prometheus-api-client-python, pull requests merged in 2019-10, with the labels that each got.

#50 py linting and coala fixes
  .zuul.yaml
  app.py
  docs/conf.py
  prometheus_api_client/__init__.py
  prometheus_api_client/prometheus_connect.py
Labels: approved, size/L

#49 Added kebechet support
  .thoth.yaml
Labels: approved, size/S

#51 Add a .coafile
  .coafile
  .zuul.yaml
  app.py
  prometheus_api_client/__init__.py
  prometheus_api_client/metric.py
  prometheus_api_client/metrics_list.py
  prometheus_api_client/prometheus_connect.py
  prometheus_api_client/utils.py
  tests/__init__.py
  tests/test_metric.py
Labels: approved, size/L

#53 merge v.0.0.2 into master
  .coafile
  .stickler.yml
  README.md
  app.py
  docs/source/prometheus_api_client.rst
  examples/MetricsList_example.ipynb
  prometheus_api_client/__init__.py
  prometheus_api_client/metric.py
  prometheus_api_client/metrics_list.py
  prometheus_api_client/prometheus_connect.py
  prometheus_api_client/utils.py
  pyproject.toml
  requirements.txt
  setup.py
  tests/__init__.py
  tests/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/up/20190728/201907281200.json
  tests/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/up/20190728/201907281800.json
  tests/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/up/20190729/201907290000.json
  tests/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/up/20190729/201907290600.json
  tests/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/up/20190729/201907291200.json
  tests/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/up/20190729/201907291800.json
  tests/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/up/20190730/201907300000.json
  tests/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/up/20190730/201907300600.json
  tests/test_metric.py
  tests/test_metrics_list.py
  tests/test_prometheus_connect.py
Labels: approved, size/XXL

#55 Add .env file for prometheus url to run pytest
  .env
Labels: approved, size/XS

#57 Add Pipfile for dependency management
  Pipfile
Labels: approved, size/S

#59 Initial dependency lock
  Pipfile.lock
Labels: bot, size/L

#54 Update README.md
  README.md
Labels: approved, size/S

#60 Update Version number to create a new release
  prometheus_api_client/__init__.py
  setup.py
Labels: approved, size/XS

#58 [WIP]Use .zuul.yaml for pytest env vars instead of .env
  .env
  .zuul.yaml
Labels: approved, do-not-merge/work-in-progress, size/M, size/S, size/XS

#63 Revert "[WIP]Use .zuul.yaml for pytest env vars instead of .env"
  .env
  .zuul.yaml
Labels: do-not-merge/work-in-progress, size/S

#64 Using env var set in zuul config
  .env
  .zuul.yaml
Labels: approved, size/S

#66 Release of version 0.2.1
  CHANGELOG.md
  prometheus_api_client/__init__.py
Labels: bot, size/M

#67 Automatic update of dependency pandas from 0.25.1 to 0.25.2
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase
