Repository 4n4nd/prometheus-api-client-python, pull requests merged in 2020-11, with the labels that each got.

#166 Update example notebook
  examples/MetricsList_example.ipynb
Labels: approved, size/XL

#167 Automatic update of dependency requests from 2.24.0 to 2.25.0
  Pipfile.lock
Labels: approved, bot, size/L

#168 Automatic update of dependency dateparser from 0.7.6 to 1.0.0
  Pipfile.lock
Labels: approved, bot, size/L

#170 Automatic update of dependency matplotlib from 3.3.2 to 3.3.3
  Pipfile.lock
Labels: approved, bot, size/L

#171 Automatic update of dependency numpy from 1.19.2 to 1.19.4
  Pipfile.lock
Labels: approved, bot, size/L

#172 Automatic update of dependency httmock from 1.3.0 to 1.4.0
  Pipfile.lock
Labels: approved, bot, size/L

#177 Add MetricRangeDataFrame to RTD. Add sphinx to Pipfile.
  Pipfile
  Pipfile.lock
  docs/source/prometheus_api_client.rst
Labels: approved, size/L

#182 feat: replaced exit with ValueError
  prometheus_api_client/prometheus_connect.py
  tests/test_prometheus_connect.py
Labels: approved, size/S

#181 Add method to check connection to Prometheus
  prometheus_api_client/prometheus_connect.py
Labels: approved, size/S
