Repository 4n4nd/prometheus-api-client-python, pull requests merged in 2020-03, with the labels that each got.

#83 Fix Lint Errors
  README.md
Labels: approved, size/S

#87 Automatic update of dependency matplotlib from 3.1.3 to 3.2.0
  Pipfile.lock
Labels: bot, size/M

#89 Resolves #86
  prometheus_api_client/__init__.py
  prometheus_api_client/metric_snapshot_df.py
  tests/test_metric_snapshot_df.py
Labels: approved, size/L

#91 Automatic update of dependency dateparser from 0.7.2 to 0.7.4
  Pipfile.lock
Labels: bot, size/XS

#92 Automatic update of dependency pandas from 1.0.1 to 1.0.2
  Pipfile.lock
Labels: bot, size/M

#84 Add Coala Linter
  .coafile
  CHANGELOG.md
  README.md
Labels: approved, size/L

#95 Automatic update of dependency pandas from 1.0.2 to 1.0.3
  Pipfile.lock
Labels: bot, size/M

#96 Automatic update of dependency matplotlib from 3.2.0 to 3.2.1
  Pipfile.lock
Labels: bot, size/M
