Repository 4n4nd/prometheus-api-client-python, pull requests merged in 2020-02, with the labels that each got.

#76 Automatic update of dependency matplotlib from 3.1.2 to 3.1.3
  Pipfile.lock
Labels: bot, size/S

#78 Automatic update of dependency pandas from 1.0.0 to 1.0.1
  Pipfile.lock
Labels: bot, size/M

#72 Replace Exception rising in PrometheusConnect class to internal one
  Pipfile
  Pipfile.lock
  docs/source/prometheus_api_client.rst
  prometheus_api_client/exceptions.py
  prometheus_api_client/prometheus_connect.py
  tests/mocked_network.py
  tests/test_prometheus_connect.py
Labels: approved, size/L

#80 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#81 Automatic update of dependency requests from 2.22.0 to 2.23.0
  Pipfile.lock
Labels: bot, size/M
