Repository 4n4nd/prometheus-api-client-python, pull requests merged in 2020-06, with the labels that each got.

#109 Template for issue creation
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, size/M

#113 Update .coafile
  .coafile
Labels: approved, size/XS

#111 Automatic update of dependency dateparser from 0.7.4 to 0.7.5
  Pipfile.lock
Labels: bot, size/L

#114 Update setup.py
  setup.py
Labels: approved, size/S

#117 Release of version 0.3.1
  CHANGELOG.md
  prometheus_api_client/__init__.py
Labels: bot, size/L

#118 Update README.md
  README.md
Labels: approved, size/XS

#120 Automatic update of dependency dateparser from 0.7.5 to 0.7.6
  Pipfile.lock
Labels: bot, size/XS

#122 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: approved, bot

#123 Automatic update of dependency pandas from 1.0.4 to 1.0.5
  Pipfile.lock
Labels: approved, bot

#124 Automatic update of dependency matplotlib from 3.2.1 to 3.2.2
  Pipfile.lock
Labels: approved, bot
