Repository 4n4nd/prometheus-api-client-python, pull requests merged in 2020-09, with the labels that each got.

#151 Release of version 0.4.1
  CHANGELOG.md
  prometheus_api_client/__init__.py
Labels: approved, bot, size/S

#153 Updating the readme
  README.md
Labels: size/L

#156 now with an OWNERS file
  OWNERS
Labels: size/XS

#159 fixes to make pre-commit happy
  OWNERS
  README.md
Labels: approved, size/XS

#154 Automatic update of dependency pandas from 1.1.1 to 1.1.2
  Pipfile.lock
Labels: approved, bot, size/M

#158 Automatic update of dependency matplotlib from 3.3.1 to 3.3.2
  Pipfile.lock
Labels: approved, bot, size/M

#155 Automatic update of dependency numpy from 1.19.1 to 1.19.2
  Pipfile.lock
Labels: approved, bot, size/M

#163 Add MetricSnapshotDataFrame,MetricRangeDataFrame basic usage to README
  README.md
Labels: approved, size/M
