Repository 4n4nd/prometheus-api-client-python, pull requests merged in 2021-06, with the labels that each got.

#210 update pytest prom url since operatefirst url is now behind a proxy
  .aicoe-ci.yaml
  README.md
Labels: approved, size/XS

#209 fix of the naming which is causing dependency update failure
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, lgtm, size/XL

#212 Update OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#213 README.md example codes fix
  README.md
Labels: approved, lgtm, size/XS
